---
title: "analysis"
author: "Nick Kathios"
date: '2022-12-02'
output: html_document
---
#loading in necessary packages
```{r}
library(tidyverse)
library(lmerTest)
library(lme4)
library(misty)
```

#loading in data
```{r}
timeseries <- read.csv(file='../data/roitimeseries.csv')
timeseries$vocal= ifelse(timeseries$vocal=="y","Y", timeseries$vocal ) #recoding some values
timeseries$seconds<- (timeseries$TR - ((timeseries$order-1)*60))*0.475 # adding seconds to df
timeseries_subcortical <- read.csv(file='../scripts/limbicroitimeseries.csv')

vocal_nonvocal <- read.csv(file='../data/vocal_nonvocal.csv')
vocal_nonvocal$vocal= ifelse(vocal_nonvocal$vocal=="y","Y", timeseries$vocal ) #recoding some values
vocal_nonvocal$liking= ifelse(vocal_nonvocal$liking=="0",NA, timeseries$liking ) #recoding some values
vocal_nonvocal$familiarity= ifelse(vocal_nonvocal$familiarity=="0",NA, timeseries$familiarity ) #recoding some values

vocal_nonvocalnlp <- read.csv(file='../data/NLP.csv') 
names(vocal_nonvocalnlp)[6] <- "SUBID"

vocal_nonvocalnlp <- vocal_nonvocalnlp %>%
  select(SUBID, stim_name, vadersenti_score)

timeseries_NLP <- merge(timeseries_subcortical, vocal_nonvocalnlp, by=c("stim_name","SUBID"))

#change "timeseries_subcortical" in line 33 to "timeseries" if you want to see auditory ROIs

covariates <- timeseries_NLP %>%
  subset(SUBID == "ASHA") %>% #pick a single participant each time
  select(TR, vadersenti_score)

covariates<-covariates[order(covariates$TR),]

TRs <- expand.grid(
  TR =  seq(1:1440)
)
 
covariates <- merge(covariates, TRs, by="TR", all = TRUE)

covariates[is.na(covariates)] <- 0

write.csv(covariates, file="../data/sentimentscores_covariates/ASHA.csv") #dont forget to delete the TR columns + the column headers
```

#data cleaning
```{r}
average_activation <-
timeseries %>%
  subset(vocal=="N") %>%
  group_by(SUBID, older_younger, self_other, sex) %>% ## here you can add which variables you'd be interested in looking at 
  summarise_at(vars(pMTGL_univariatecluster), list(name = mean)) ##if you want to look at different ROIs, update the variable in the "vars()" argument to whichever column ROI you want

names(average_activation)[5] = "average" #renaming the output of previous function

average_activation$self_other<-as.factor(average_activation$older_younger)#if you are interested in another binary variable, just update this to the variable you're using (i.e. "average_activation$[VARIABLE NAME]" in parentheses)

#contrasts(average_activation$sex)<-c(-0.5,0.5) #if you are interested in another binary variable, just update this to the variable you're using (i.e. "average_activation$[VARIABLE NAME]" in parentheses)

test<-lmer(average~older_younger + (1|SUBID), data=average_activation) #I can explain these stats the next time we meet-- a significant p-value for older_younger1 = a significant effect of age; you can update the "older_younger" variable to test which ones you're interested in
summary(test)
```

#plotting timeseries
```{r}
## just messy stuff in this chunk
timeseries_stimothervocal <- subset(timeseries, Stim == 13) # you can pick any stimuli, but I chose 15 here b/c it is other-selected (i.e. everyone heard it) + it has vocals.

onset_value <- 
  timeseries_stimothervocal %>%
  group_by(SUBID) %>%
  subset(seconds==0.475) %>%
  mutate(
    onset_value = aSTGl #update ROI here
  )
onset_value <- cbind(onset_value[3],onset_value[28])

timeseries_stimothervocal <- merge(timeseries_stimothervocal, onset_value, by.x="SUBID", by.y="SUBID")
timeseries_stimothervocal <- 
  timeseries_stimothervocal %>%
  group_by(SUBID) %>%
  mutate(
    scaled = ((aSTGl - onset_value)/sd(aSTGl)) #update ROI here as well
  )

ggplot(timeseries_stimothervocal, aes(x=round(seconds), y=scaled)) + #to change the ROI you're plotting, change this y-value
  geom_smooth() +
  theme_classic() +
  xlab("Time (s)") +
  ylab("Scaled ROI Activity") +
  ggtitle("pMTG Left Cluster from Univariate Analysis, Stimulus 15 (Vocal)") +
  theme(plot.title = element_text(face="bold", hjust = 0.5))

#ggsave('pMTGLTimeseriesUnivariate15.png', plot= plot, dpi=350)

## Plotting timeseries of other-selected nonvocal trial
timeseries_stimothernonvocal <- subset(timeseries, Stim == 16) # you can pick any stimuli, but I chose 15 here b/c it is other-selected (i.e. everyone heard it) + it *does not* have vocals.

onset_value <- 
  timeseries_stimothernonvocal %>%
  group_by(SUBID) %>%
  subset(seconds==0.475) %>%
  mutate(
    onset_value = aSTGl #update ROIs here
  )
onset_value <- cbind(onset_value[3],onset_value[28])

timeseries_stimothernonvocal <- merge(timeseries_stimothernonvocal, onset_value, by.x="SUBID", by.y="SUBID")

timeseries_stimothernonvocal <- 
  timeseries_stimothernonvocal %>%
  group_by(SUBID) %>%
  mutate(
    scaled = ((aSTGl  - onset_value)/sd(aSTGl)) #update ROIs here
  )

ggplot(timeseries_stimothernonvocal, aes(x=round(seconds), y=scaled)) +
  geom_smooth()+
  theme_light()+
  xlab("time (s)") +
  ylab("Scaled ROI Activity") 
  #ggtitle("pMTG Left Cluster from Univariate Analysis, Stimulus 16 (Nonvocal)") #update labels

#ggsave('pMTGLTimeseries16Univariate.png', plot= plot2, dpi=350)
```

```{r}
## doing roi-analyses for all music (i.e. vocal v non-vocal)
timeseries_other <- subset(timeseries, self_other=="other")

onset_value <- 
  timeseries_other %>%
  group_by(SUBID, Stim) %>%
  subset(seconds==0.475) %>%
  mutate(
    onset_value = pMTGL_univariatecluster #update ROIs here
  )

onset_value <- cbind(onset_value[3],onset_value[5],onset_value[28])

timeseries_stimother <- merge(timeseries_other, onset_value, by.x=c("SUBID","Stim"), by.y=c("SUBID", "Stim"))

timeseries_stimother <-
  timeseries_stimother %>%
  group_by(SUBID, Stim) %>%
  mutate(
    scaled = ((pMTGL_univariatecluster - onset_value)/sd(pMTGL_univariatecluster)) #update ROIs here
  )

ggplot(timeseries_stimother, aes(x=round(seconds), y=scaled)) + 
  geom_smooth(aes(color=vocal, fill=vocal))+
  theme_classic() +
  xlab("Time (s)") +
  ylab("Scaled ROI Activity") +
  ggtitle("pMTG Left Cluster") +#update labels
  theme(plot.title = element_text(face="bold", hjust = 0.5, size=18), axis.text=element_text(size=15), axis.title=element_text(size=15))

ggsave('pMTGLTimeseriesAllComparison.png', plot = last_plot(), dpi=350) #uncomment when saving
```

```{r}
##two stimuli one time series ##
timeseries_other <- subset(timeseries, self_other=="other")

onset_value <- 
  timeseries_other %>%
  group_by(SUBID, Stim) %>%
  subset(seconds==0.475) %>%
  mutate(
    onset_value = pMTGR_univariatecluster #update ROIs here
  )

onset_value <- cbind(onset_value[3],onset_value[5],onset_value[28])

timeseries_stimother <- merge(timeseries_other, onset_value, by.x=c("SUBID","Stim"), by.y=c("SUBID", "Stim"))

timeseries_stimother <-
  timeseries_stimother %>%
  group_by(SUBID, Stim) %>%
  mutate(
    scaled = ((pMTGR_univariatecluster - onset_value)/sd(pMTGR_univariatecluster)) #update ROIs here
  )

timeseries_otherselected <-
  timeseries_stimother %>%
  subset(Stim == 8 | Stim == 15 | Stim == 7 | Stim == 9 | Stim == 14 | Stim == 16) #pick stims want to compare

timeseries_otherselected$vocals <- ifelse(timeseries_otherselected$Stim==15 | timeseries_otherselected$Stim==8,  "Non-English", "Nonvocal")
timeseries_otherselected$Stim <- as.factor(timeseries_otherselected$Stim) 

ggplot(timeseries_otherselected, aes(x=round(seconds), y=scaled)) + 
  geom_smooth(aes(color=factor(vocals, labels = c("Non-English Vocal", "Nonvocal")), fill=factor(vocals, labels = c("Non-English Vocal", "Nonvocal"))), alpha=0.2) +
  theme_classic()+
  labs(x= "Time (s)", y="Scaled ROI Activity", color="stimulus type", fill="stimulus type")+
  ggtitle("pMTG Right Cluster") +
  theme(plot.title = element_text(face="bold", size = 18, hjust=0.5), axis.text=element_text(size=15), axis.title=element_text(size=15)) +
  scale_color_manual(values=c("#00BA38", "#F8766D")) +
  scale_fill_manual(values=c("#00BA38", "#F8766D")) #F8766D


ggsave('pMTGRnonvocalvsnonEnglish.png', plot = last_plot(), scale=1, dpi=350)
```

```{r}
### statistics: english vs. non-verbal
average_activation <-
timeseries %>%
   group_by(SUBID, Stim) %>%
  #subset(vocal=="Y") %>%
  subset(self_other=="other") %>%
  subset(Stim == 8 | Stim == 15 | Stim == 7 | Stim == 9 | Stim == 14 | Stim == 16) %>% #pick stims want to compare %>% ## pick which stimuli you'd like to pick
  summarise_at(vars(pMTGR_univariatecluster), list(name = mean)) ##if you want to look at different ROIs, update the variable in the "vars()" argument to whichever column ROI you want

average_activation$vocals <- ifelse(average_activation$Stim==15 | average_activation$Stim==8,  "Non-English", "English")
average_activation$Stim <- as.factor(average_activation$Stim)

names(average_activation)[3] = "average" #renaming the output of previous function

test<-lmer(average~vocals + (1|SUBID) + (1|Stim), data=average_activation) #I can explain these stats the next time we meet-- a significant p-value for older_younger1 = a significant effect of age; you can update the "older_younger" variable to test which ones you're interested in
summary(test) ## all music
```

```{r}
##all together 

timeseries_other <- subset(timeseries, self_other=="other")

onset_value <- 
  timeseries_other %>%
  group_by(SUBID, Stim) %>%
  subset(seconds==0.475) %>%
  mutate(
    onset_value = pMTGR_univariatecluster #update ROIs here
  )

onset_value <- cbind(onset_value[3],onset_value[5],onset_value[28])

timeseries_stimother <- merge(timeseries_other, onset_value, by.x=c("SUBID","Stim"), by.y=c("SUBID", "Stim"))

timeseries_stimother <-
  timeseries_stimother %>%
  group_by(SUBID, Stim) %>%
  mutate(
    scaled = ((pMTGR_univariatecluster - onset_value)/sd(pMTGR_univariatecluster)) #update ROIs here
  )

timeseries_otherselected <-
  timeseries_stimother %>%
  subset(Stim == 8 | Stim == 15 | Stim == 10 | Stim == 7) #pick stims want to compare

ggplot(timeseries_otherselected, aes(x=round(seconds), y=scaled)) + 
  geom_smooth(aes(color=factor(Stim, labels = c("Nonvocal", "Nonverbal", "English", "Other Language")), fill=factor(Stim, labels = c("Nonvocal", "Nonverbal", "English", "Other Language"))))+
  theme_classic()+
  labs(x= "Time (s)", y="Scaled ROI Activity", color="vocal type", fill="vocal type")+
  ggtitle("pMTG Right Cluster") + #update labels
  theme(plot.title = element_text(face="bold", size = 18, hjust=0.5), axis.text=element_text(size=15), axis.title=element_text(size=15))
ggsave('pMTGRallvocaltypes.png', plot = last_plot(), scale=1, dpi=350)
```

```{r}
## Plotting timeseries of other-selected vocal trial Stim 11
timeseries_stimothervocal <- subset(timeseries, Stim == 11) # you can pick any stimuli, but I chose 15 here b/c it is other-selected (i.e. everyone heard it) + it has vocals.

onset_value <- 
  timeseries_stimothervocal %>%
  group_by(SUBID) %>%
  subset(seconds==0.475) %>%
  mutate(
    onset_value = pMTGL_univariatecluster #update ROI here
  )
onset_value <- cbind(onset_value[3],onset_value[28])

timeseries_stimothervocal <- merge(timeseries_stimothervocal, onset_value, by.x="SUBID", by.y="SUBID")
timeseries_stimothervocal <- 
  timeseries_stimothervocal %>%
  group_by(SUBID) %>%
  mutate(
    scaled = ((pMTGL_univariatecluster - onset_value)/sd(pMTGL_univariatecluster)) #update ROI here as well
  )

ggplot(timeseries_stimothervocal, aes(x=round(seconds), y=scaled)) + #to change the ROI you're plotting, change this y-value
  geom_smooth() +
  theme_classic() +
  annotate(xmin = 0, xmax = 3, ymin = -Inf, ymax = Inf, geom = 'rect', alpha = 0.2, fill="#56B4E9") +
  annotate(xmin = 4, xmax = 8, ymin = -Inf, ymax = Inf, geom = 'rect', alpha = 0.2, fill="#56B4E9")+
  annotate(xmin = 9, xmax = 13, ymin = -Inf, ymax = Inf, geom = 'rect', alpha = 0.2, fill="#56B4E9")+
  annotate(xmin = 14, xmax = 20, ymin = -Inf, ymax = Inf, geom = 'rect', alpha = 0.2, fill="#56B4E9")+
  #annotate(geom = "text",x = 11, y= 0,label="Vocals \nPresent", fontface="bold",size=6)
  labs(x= "Time (s)", y="Scaled ROI Activity")+
  ggtitle("Stimulus 11: \"Hurt\"") + #update labels
  theme(plot.title = element_text(face="bold", size = 18, hjust=0.5), axis.text=element_text(size=15), axis.title=element_text(size=15))

ggsave('pMTGLStim11.png', plot = last_plot(), scale=1, dpi=350)

```

```{r}
## Plotting timeseries of other-selected vocal trial
timeseries_stimothervocal <- subset(timeseries, Stim == 8) # you can pick any stimuli, but I chose 15 here b/c it is other-selected (i.e. everyone heard it) + it has vocals.

onset_value <- 
  timeseries_stimothervocal %>%
  group_by(SUBID) %>%
  subset(seconds==0.475) %>%
  mutate(
    onset_value = pMTGR_univariatecluster #update ROI here
  )
onset_value <- cbind(onset_value[3],onset_value[28])

timeseries_stimothervocal <- merge(timeseries_stimothervocal, onset_value, by.x="SUBID", by.y="SUBID")
timeseries_stimothervocal <- 
  timeseries_stimothervocal %>%
  group_by(SUBID) %>%
  mutate(
    scaled = ((pMTGR_univariatecluster - onset_value)/sd(pMTGR_univariatecluster)) #update ROI here as well
  )

ggplot(timeseries_stimothervocal, aes(x=round(seconds), y=scaled)) + #to change the ROI you're plotting, change this y-value
  geom_smooth() +
  theme_classic() +
  annotate(xmin = 0, xmax = 15, ymin = -Inf, ymax = Inf, geom = 'rect', alpha = 0.2, fill="#56B4E9") +
  #annotate(geom = "text",x = 11, y= 0,label="Vocals \nPresent", fontface="bold",size=6)
  labs(x= "Time (s)", y="Scaled ROI Activity") +
  ggtitle(expression(bold("Stimulus 8: ") * bolditalic("Symphony No. 2, Finale"))) + #update labels
  theme(plot.title = element_text(face="bold", size = 18, hjust=0.5), axis.text=element_text(size=15), axis.title=element_text(size=15))

ggsave('pMTGRStim8.png', plot = last_plot(), scale=1, dpi=350)

```

```{r}
## Plotting timeseries of other-selected vocal trial
timeseries_stimothervocal <- subset(timeseries, Stim == 10) # you can pick any stimuli, but I chose 15 here b/c it is other-selected (i.e. everyone heard it) + it has vocals.

onset_value <- 
  timeseries_stimothervocal %>%
  group_by(SUBID) %>%
  subset(seconds==0.475) %>%
  mutate(
    onset_value = pMTGR_univariatecluster #update ROI here
  )
onset_value <- cbind(onset_value[3],onset_value[28])

timeseries_stimothervocal <- merge(timeseries_stimothervocal, onset_value, by.x="SUBID", by.y="SUBID")
timeseries_stimothervocal <- 
  timeseries_stimothervocal %>%
  group_by(SUBID) %>%
  mutate(
    scaled = ((pMTGR_univariatecluster - onset_value)/sd(pMTGR_univariatecluster)) #update ROI here as well
  )

ggplot(timeseries_stimothervocal, aes(x=round(seconds), y=scaled)) + #to change the ROI you're plotting, change this y-value
  geom_smooth() +
  theme_classic() +
  annotate(xmin = 0, xmax = 17, ymin = -Inf, ymax = Inf, geom = 'rect', alpha = 0.2, fill="#56B4E9") +
  #annotate(geom = "text",x = 11, y= 0,label="Vocals \nPresent", fontface="bold",size=6)
  labs(x= "Time (s)", y="Scaled ROI Activity")+
  ggtitle("Stimulus 10: \"John Wayne Gacy, Jr.\"") + #update labels
  theme(plot.title = element_text(face="bold", size = 18, hjust=0.5), axis.text=element_text(size=15), axis.title=element_text(size=15))

ggsave('pMTGRStim10.png', plot = last_plot(), scale=1, dpi=350)

```

```{r}
## Plotting timeseries of other-selected vocal trial Stim 12,13,15
timeseries_stimothervocal <- subset(timeseries, Stim == 15) # you can pick any stimuli, but I chose 15 here b/c it is other-selected (i.e. everyone heard it) + it has vocals.

onset_value <- 
  timeseries_stimothervocal %>%
  group_by(SUBID) %>%
  subset(seconds==0.475) %>%
  mutate(
    onset_value = pMTGR_univariatecluster #update ROI here
  )
onset_value <- cbind(onset_value[3],onset_value[28])

timeseries_stimothervocal <- merge(timeseries_stimothervocal, onset_value, by.x="SUBID", by.y="SUBID")
timeseries_stimothervocal <- 
  timeseries_stimothervocal %>%
  group_by(SUBID) %>%
  mutate(
    scaled = ((pMTGR_univariatecluster - onset_value)/sd(pMTGR_univariatecluster)) #update ROI here as well
  )

ggplot(timeseries_stimothervocal, aes(x=round(seconds), y=scaled)) + #to change the ROI you're plotting, change this y-value
  geom_smooth() +
  theme_classic() +
  annotate(xmin = 0, xmax = 20, ymin = -Inf, ymax = Inf, geom = 'rect', alpha = 0.2, fill="#56B4E9") +
  #annotate(geom = "text",x = 11, y= 0,label="Vocals \nPresent", fontface="bold",size=6)
  labs(x= "Time (s)", y="Scaled ROI Activity")+
  ggtitle(expression(bold("Stimulus 15: ") * bolditalic("Nessun Dorma"))) + #update labels
  theme(plot.title = element_text(face="bold", size = 18, hjust=0.5), axis.text=element_text(size=15), axis.title=element_text(size=15))

ggsave('pMTGRStim15.png', plot = last_plot(), scale=1, dpi=350)

```

#investigating differences in liking + familiarity
```{r}
vocal_nonvocal_other <- 
  vocal_nonvocal %>%
  subset(self_other=="other") %>%
  subset(MCI!="Y")

m1 <- lmer(liking ~ vocal + older_younger + (1|participant_ID), data=vocal_nonvocal_other)
summary(m1)

m1 <- lmer(familiarity ~ vocal + older_younger + (1|participant_ID), data=vocal_nonvocal_other)
summary(m1)
```

#sentiment score analysis
#data cleaning
```{r}
timeseries_NLP <-
timeseries %>% 
  select(SUBID, TR, aSTGl, aSTGr, pMTGL_univariatecluster, pMTGR_univariatecluster) %>% #pMTG extract from our paper, aSTG as informed by norman-haignere
  merge(timeseries_NLP, by=c("SUBID", "TR"))
average_activation <-
timeseries_NLP %>%
  subset(vocal=="Y") %>%
  group_by(SUBID, older_younger, self_other, sex, vadersenti_score, stim_name) %>% ## here you can add which variables you'd be interested in looking at 
  summarise_at(vars(hippocampusr), list(name = mean)) ##if you want to look at different ROIs, update the variable in the "vars()" argument to whichever column ROI you want

names(average_activation)[7] = "average" #renaming the output of previous function

average_activation$vadersenti_score <- as.numeric(average_activation$vadersenti_score)

test<-lmer(average~vadersenti_score + (1|SUBID) + (1|stim_name), data=average_activation) #I can explain these stats the next time we meet-- a significant p-value for older_younger1 = a significant effect of age; you can update the "older_younger" variable to test which ones you're interested in
summary(test) ## all music
```

```{r}
## let's test just other-selected w/ vocals
average_activation <-
timeseries_NLP %>%
  subset(vocal=="Y") %>%
  subset(self_other=="other") %>%
  group_by(SUBID, older_younger, sex, vadersenti_score,stim_name) %>% ## here you can add which variables you'd be interested in looking at 
  summarise_at(vars(aSTGl), list(name = mean)) ##if you want to look at different ROIs, update the variable in the "vars()" argument to whichever column ROI you want

names(average_activation)[6] = "average" #renaming the output of previous function

average_activation$vadersenti_score <- as.numeric(average_activation$vadersenti_score)

test<-lmer(average~vadersenti_score + (1|SUBID) + (1|stim_name), data=average_activation) 
summary(test)

## let's test just self-selected w/ vocals
average_activation <-
timeseries_NLP %>%
  subset(vocal=="Y") %>%
  subset(self_other=="self") %>%
  group_by(SUBID, older_younger, sex, vadersenti_score,stim_name) %>% ## here you can add which variables you'd be interested in looking at 
  summarise_at(vars(amygdalal), list(name = mean)) ##if you want to look at different ROIs, update the variable in the "vars()" argument to whichever column ROI you want

names(average_activation)[6] = "average" #renaming the output of previous function

average_activation$vadersenti_score <- as.numeric(average_activation$vadersenti_score)

test<-lmer(average~vadersenti_score + (1|SUBID), data=average_activation)
summary(test)

##plotting
ggplot(data=average_activation, aes(x=vadersenti_score, y=average))+
  geom_point() +
  theme_classic()
```