---
title: "CONN_MIRanalysis"
author: "Nick Kathios"
date: "2023-09-15"
output: html_document
---

```{r}
library(tidyverse)
library(lme4)
library(lmerTest)
```

```{r}
vocal_nonvocal<- read.csv('../data/vocal_nonvocal.csv')
CONN_ID <- read.csv('../data/CONN_ID.csv')

ID <- read.csv('../data/CONN_ID.csv') %>%
  subset(!is.na(CONN.id))

MIR <- read.csv(file='../data/audioExtraction.csv')
names <- ID$X

TRS <- seq(1,1440,1)

aMTGl <- read.csv(file='aMTGlTSCONN.csv', header=F)
aMTGl <- aMTGl[-(1:947),]
colnames(aMTGl) = names 
aMTGl <- cbind(aMTGl, TRS) %>%
  pivot_longer(`190716FKEE1`:`200211DCAT1`, values_to = "aMTGl")

aMTGr <- read.csv(file='aMTGrTSCONN.csv', header=F)
aMTGr <- aMTGr[-(1:947),] 
colnames(aMTGr) = names 
aMTGr <- cbind(aMTGr, TRS) %>%
  pivot_longer(`190716FKEE1`:`200211DCAT1`, values_to = "aMTGr")

pMTGr <- read.csv(file='pMTGrTSCONN.csv', header=F)
pMTGr <- pMTGr[-(1:947),]
colnames(pMTGr) = names 
pMTGr <- cbind(pMTGr, TRS) %>%
  pivot_longer(`190716FKEE1`:`200211DCAT1`, values_to = "pMTGr")

pMTGl <- read.csv(file='pMTGlTSCONN.csv', header=F)
pMTGl <- pMTGl[-(1:947),]
colnames(pMTGl) = names 
pMTGl <- cbind(pMTGl, TRS) %>%
  pivot_longer(`190716FKEE1`:`200211DCAT1`, values_to = "pMTGl")

aSTGl <- read.csv(file='aSTGlTSCONN.csv', header=F)
aSTGl <- aSTGl[-(1:947),]
colnames(aSTGl) = names 
aSTGl <- cbind(aSTGl, TRS) %>%
  pivot_longer(`190716FKEE1`:`200211DCAT1`, values_to = "aSTGl")

aSTGr <- read.csv(file='aSTGlTSCONN.csv', header=F)
aSTGr <- aSTGr[-(1:947),]
colnames(aSTGr) = names 
aSTGr <- cbind(aSTGr, TRS) %>%
  pivot_longer(`190716FKEE1`:`200211DCAT1`, values_to = "aSTGr")

HGl <- read.csv(file='HGlTSCONN.csv', header=F)
HGl <- HGl[-(1:947),]
colnames(HGl) = names 
HGl <- cbind(HGl, TRS) %>%
  pivot_longer(`190716FKEE1`:`200211DCAT1`, values_to = "HGl")


#put all data frames into list
df_list <- list(aMTGl, aMTGr, aSTGl, aSTGr, pMTGl, pMTGr, HGl)

#merge all data frames in list
master <- df_list %>% reduce(full_join, by=c('name','TRS')) 
master$SUBID<-gsub('[[:digit:]]+', '',master$name)
```

#get TRs w/ coded data
```{r}
ID = Sys.glob('../data/MRI_mus-bid_task/**********1_mus-bid-biddata.txt')
post_df = ID %>% 
  map_dfr(read_table, .id = "source")


post_df$source <- as.integer(post_df$source)
source <- seq(1,71,by=1)
ID <- cbind(source,ID)

post_df <- merge(post_df, ID, by.y ="source", by.x="source") 

post_df$ID <-  gsub("1_mus-bid-biddata.txt", "", post_df$ID)
post_df$ID <-  gsub("../data/MRI_mus-bid_task/", "", post_df$ID)

names(post_df)<- c("Source", "Stim", "Liking", "Familiarity", "SUBID")

post_df<- subset(post_df, select=c("Stim", "SUBID"))
#to do: merge w/ vocal-nonvocal & expand df to have all TRs
post_df$SUBID<-gsub('[[:digit:]]+', '',post_df$SUBID)
onsets_stim <- merge(post_df, vocal_nonvocal, by.x=c("SUBID", "Stim"), by.y=c("participant_ID", "stim_ID"))


stim_order <- seq(1,24,1)
stim_order <- as.data.frame(rep(stim_order, 60))
TRs<- as.data.frame(seq(1,1440,1))
names(stim_order) <- "order"
names(TRs) <- "TR"

stim_order$order <- arrange(stim_order, order)
TRs <- cbind(stim_order$order, TRs)

TRs_vocalnonvocal<-merge(TRs, onsets_stim, by.x="order",by.y="stim_order")
```


#cleaning ROI-stim orde
```{r}
roistim_order <- read.csv('../data/roi_participantorder.csv')

roi_ID <- seq(1,71,1)
roi_ID <- as.data.frame(rep(roi_ID, 1440))
names(roi_ID) <- "ID"
roi_ID <- arrange(roi_ID, ID)

TRs<- (seq(1,1440,1))
TRs_roi<- as.data.frame(rep(TRs, 71))
names(TRs_roi) <- "TR"
roi_data<-cbind(TRs_roi, roi_ID)
```

#merge coded data w/ TRs
```{r}
#merge
roistim_order <- subset(roistim_order, roi_order <= 18 | roi_order >= 36)

roi_dataID<- merge(roi_data, roistim_order, by.x = "ID", by.y="roi_order")

attempt <- merge(TRs_vocalnonvocal, roi_dataID, by.x=c("TR", "SUBID"), by.y=c("TR","SUBID"))

#isolate just music-listening TR
x=1:77760
for (i in x){
  if (attempt$TR[i] >= (60*(attempt$order[i]-1)+43) & attempt$TR[i] <= (60*(attempt$order[i]-1)+60)){
    attempt$TR[i] = NA
  }
}

attempt<-attempt[!is.na(attempt$TR),]
attempt<-subset(attempt, Stim < 17)

master_final <- merge(attempt, master, by.x = c("TR", "SUBID"), by.y=c("TRS", "SUBID")) %>%
  merge(MIR, by="Stim")

x=1:nrow(master_final)
for (i in x){
    master_final$cor[i] = mean(cor(master_final[i,21:27]))
}

```