---
title: "final_analysis"
author: "Nick Kathios"
date: '2022-12-02'
output: html_document
---
#loading in necessary packages
```{r}
library(tidyverse)
library(lmerTest)
library(lme4)
library(misty)
library(ggrepel)
```

#loading in data
```{r}
timeseries <- read.csv(file='../data/roitimeseries.csv')
timeseries$vocal= ifelse(timeseries$vocal=="y","Y", timeseries$vocal ) #recoding some values
timeseries$seconds<- (timeseries$TR - ((timeseries$order-1)*60))*0.475 # adding seconds to df

vocal_nonvocal <- read.csv(file='../data/vocal_nonvocal.csv')
vocal_nonvocal$vocal= ifelse(vocal_nonvocal$vocal=="y","Y", timeseries$vocal ) #recoding some values
vocal_nonvocal$liking= ifelse(vocal_nonvocal$liking=="0",NA, timeseries$liking ) #recoding some values
vocal_nonvocal$familiarity= ifelse(vocal_nonvocal$familiarity=="0",NA, timeseries$familiarity ) #recoding some values

```
#older vs. younger comparisons
```{r}
timeseries_vocal <- subset(timeseries, timeseries$vocal=="Y")

time_seriespeak<-
timeseries %>%
  subset((seconds) >=6) %>%
  subset((seconds) <= 8)


test<-lmer(pMTGL_univariatecluster~older_younger + (1|SUBID), data=time_seriespeak) #random intercepts
summary(test)

#sex comparison
test<-lmer(pMTGL_univariatecluster~sex + (1|SUBID), data=time_seriespeak) #random intercepts
summary(test)
```

```{r}
## doing roi-analyses for all music (i.e. vocal v non-vocal)
timeseries_other <- subset(timeseries, self_other=="other")

onset_value <- 
  timeseries_other %>%
  group_by(SUBID, Stim) %>%
  subset(seconds==0.475) %>%
  mutate(
    onset_value = pMTGL_univariatecluster #update ROIs here
  )

onset_value <- cbind(onset_value[3],onset_value[5],onset_value[28])

timeseries_stimother <- merge(timeseries_other, onset_value, by.x=c("SUBID","Stim"), by.y=c("SUBID", "Stim"))

timeseries_stimother <-
  timeseries_stimother %>%
  group_by(SUBID, Stim) %>%
  mutate(
    scaled = ((pMTGL_univariatecluster - onset_value)/sd(pMTGL_univariatecluster)) #update ROIs here
  )

label<-
  expand.grid(
    vocal=c("Nonvocal", "Vocal"),
    seconds=12
  )
label$scaled <- ifelse(label$vocal=="Vocal", 1.25, 0.25)
timeseries_stimother$vocal <- ifelse(timeseries_stimother$vocal=="Y", "Vocal", "Nonvocal")

ggplot(timeseries_stimother, aes(x=round(seconds), y=scaled)) + 
  annotate(xmin = 6, xmax = 8, ymin = -Inf, ymax = Inf, geom = 'rect', alpha = 0.4, fill="#F0E442") +
  geom_smooth(aes(color=vocal, fill=vocal))+
  theme_classic() +
  xlab("Time (s)") +
  ylab("Scaled ROI Activity") +
  ggtitle("pMTG Left Cluster") +#update labels
  theme(plot.title = element_text(face="bold", hjust = 0.5, size=18), axis.text=element_text(size=15), axis.title=element_text(size=15))+
  geom_label_repel(aes(label = vocal, x=seconds, y=scaled, color=vocal),
                   na.rm = TRUE,
                   data=label,
                   min.segment.length = Inf,
                   point.size = NA,
                   family="Arial",
                   size=8
                   ) +
  scale_color_manual(values = c("#D55E00", "#56B4E9"))+
  scale_fill_manual(values = c("#D55E00", "#56B4E9"))+
  theme(legend.position = "none")

#ggsave('pMTGLTimeseriesAllComparison.png', plot = last_plot(), dpi=350) #uncomment when saving
```

#non-english vs english comparison
```{r}
timeseries_language <-
  time_seriespeak%>%
  subset(Stim == 8 | Stim == 15 | Stim == 10 | Stim == 11 | Stim == 12 | Stim == 13 ) #pick stims want to compare

timeseries_language$language <- ifelse(timeseries_language$Stim == 8 | timeseries_language$Stim == 15, "Non-English", "English")

test<-lmer(pMTGL_univariatecluster ~ language + (1|SUBID), data=timeseries_language) #random  intercepts
summary(test)
```

#non-english vs non-vocal comparison
```{r}
timeseries_language <-
  time_seriespeak%>%
  subset(Stim == 8 | Stim == 15 | Stim == 9 | Stim == 7 | Stim == 14 | Stim == 17 )

timeseries_language$language <- ifelse(timeseries_language$Stim == 8 | timeseries_language$Stim == 15, "Non-English", "Non-Vocal")
test<-lmer(pMTGR_univariatecluster ~ language + (1|SUBID), data=timeseries_language) #random intercepts
summary(test)
```

#plotting timeseries
```{r}
## just messy stuff in this chunk
timeseries_stimothervocal <- subset(timeseries, Stim == 13) # you can pick any stimuli, but I chose 15 here b/c it is other-selected (i.e. everyone heard it) + it has vocals.

onset_value <- 
  timeseries_stimothervocal %>%
  group_by(SUBID) %>%
  subset(seconds==0.475) %>%
  mutate(
    onset_value = aSTGl #update ROI here
  )
onset_value <- cbind(onset_value[3],onset_value[28])

timeseries_stimothervocal <- merge(timeseries_stimothervocal, onset_value, by.x="SUBID", by.y="SUBID")
timeseries_stimothervocal <- 
  timeseries_stimothervocal %>%
  group_by(SUBID) %>%
  mutate(
    scaled = ((aSTGl - onset_value)/sd(aSTGl)) #update ROI here as well
  )

ggplot(timeseries_stimothervocal, aes(x=round(seconds), y=scaled)) + #to change the ROI you're plotting, change this y-value
  geom_smooth() +
  theme_classic() +
  xlab("Time (s)") +
  ylab("Scaled ROI Activity") +
  ggtitle("pMTG Left Cluster from Univariate Analysis, Stimulus 15 (Vocal)") +
  theme(plot.title = element_text(face="bold", hjust = 0.5))

#ggsave('pMTGLTimeseriesUnivariate15.png', plot= plot, dpi=350)

## Plotting timeseries of other-selected nonvocal trial
timeseries_stimothernonvocal <- subset(timeseries, Stim == 16) # you can pick any stimuli, but I chose 15 here b/c it is other-selected (i.e. everyone heard it) + it *does not* have vocals.

onset_value <- 
  timeseries_stimothernonvocal %>%
  group_by(SUBID) %>%
  subset(seconds==0.475) %>%
  mutate(
    onset_value = aSTGl #update ROIs here
  )
onset_value <- cbind(onset_value[3],onset_value[28])

timeseries_stimothernonvocal <- merge(timeseries_stimothernonvocal, onset_value, by.x="SUBID", by.y="SUBID")

timeseries_stimothernonvocal <- 
  timeseries_stimothernonvocal %>%
  group_by(SUBID) %>%
  mutate(
    scaled = ((aSTGl  - onset_value)/sd(aSTGl)) #update ROIs here
  )

ggplot(timeseries_stimothernonvocal, aes(x=round(seconds), y=scaled)) +
  geom_smooth()+
  theme_light()+
  xlab("time (s)") +
  ylab("Scaled ROI Activity") 
  #ggtitle("pMTG Left Cluster from Univariate Analysis, Stimulus 16 (Nonvocal)") #update labels

#ggsave('pMTGLTimeseries16Univariate.png', plot= plot2, dpi=350)
```

```{r}
## doing roi-analyses for all music (i.e. vocal v non-vocal)
timeseries_other <- subset(timeseries, self_other=="other")

onset_value <- 
  timeseries_other %>%
  group_by(SUBID, Stim) %>%
  subset(seconds==0.475) %>%
  mutate(
    onset_value = pMTGL_univariatecluster #update ROIs here
  )

onset_value <- cbind(onset_value[3],onset_value[5],onset_value[28])

timeseries_stimother <- merge(timeseries_other, onset_value, by.x=c("SUBID","Stim"), by.y=c("SUBID", "Stim"))

timeseries_stimother <-
  timeseries_stimother %>%
  group_by(SUBID, Stim) %>%
  mutate(
    scaled = ((pMTGL_univariatecluster - onset_value)/sd(pMTGL_univariatecluster)) #update ROIs here
  )

ggplot(timeseries_stimother, aes(x=round(seconds), y=scaled)) + 
  geom_smooth(aes(color=vocal, fill=vocal))+
  theme_classic() +
  xlab("Time (s)") +
  ylab("Scaled ROI Activity") +
  ggtitle("pMTG Left Cluster") +#update labels
  theme(plot.title = element_text(face="bold", hjust = 0.5, size=18), axis.text=element_text(size=15), axis.title=element_text(size=15)) 

ggsave('pMTGLTimeseriesAllComparison.png', plot = last_plot(), dpi=350) #uncomment when saving
```

```{r}
##two stimuli one time series ##

timeseries_other <- subset(timeseries, self_other=="other")

onset_value <- 
  timeseries_other %>%
  group_by(SUBID, Stim) %>%
  subset(seconds==0.475) %>%
  mutate(
    onset_value = pMTGR_univariatecluster #update ROIs here
  )

onset_value <- cbind(onset_value[3],onset_value[5],onset_value[28])

timeseries_stimother <- merge(timeseries_other, onset_value, by.x=c("SUBID","Stim"), by.y=c("SUBID", "Stim"))

timeseries_stimother <-
  timeseries_stimother %>%
  group_by(SUBID, Stim) %>%
  mutate(
    scaled = ((pMTGR_univariatecluster - onset_value)/sd(pMTGR_univariatecluster)) #update ROIs here
  )

timeseries_otherselected <-
  timeseries_stimother %>%
  subset(Stim == 8 | Stim == 10) #pick stims want to compare

ggplot(timeseries_otherselected, aes(x=round(seconds), y=scaled)) + 
  geom_smooth(aes(color=factor(Stim, labels = c("Nonverbal", "English")), fill=factor(Stim, labels = c("Nonverbal", "English"))))+
  theme_classic()+
  labs(x= "Time (s)", y="Scaled ROI Activity", color="vocal type", fill="vocal type")+
  ggtitle("pMTG Right Cluster") +
  theme(plot.title = element_text(face="bold", size = 18, hjust=0.5), axis.text=element_text(size=15), axis.title=element_text(size=15))
  ggsave('pMTGREnglishvsNonverbal.png', plot = last_plot(), scale=1, dpi=350)

```

```{r}
##all together 

timeseries_other <- subset(timeseries, self_other=="other")

onset_value <- 
  timeseries_other %>%
  group_by(SUBID, Stim) %>%
  subset(seconds==0.475) %>%
  mutate(
    onset_value = pMTGR_univariatecluster #update ROIs here
  )

onset_value <- cbind(onset_value[3],onset_value[5],onset_value[28])

timeseries_stimother <- merge(timeseries_other, onset_value, by.x=c("SUBID","Stim"), by.y=c("SUBID", "Stim"))

timeseries_stimother <-
  timeseries_stimother %>%
  group_by(SUBID, Stim) %>%
  mutate(
    scaled = ((pMTGR_univariatecluster - onset_value)/sd(pMTGR_univariatecluster)) #update ROIs here
  )

timeseries_otherselected <-
  timeseries_stimother %>%
  subset(Stim == 8 | Stim == 15 | Stim == 10 | Stim == 7) #pick stims want to compare

ggplot(timeseries_otherselected, aes(x=round(seconds), y=scaled)) + 
  geom_smooth(aes(color=factor(Stim, labels = c("Nonvocal", "Nonverbal", "English", "Other Language")), fill=factor(Stim, labels = c("Nonvocal", "Nonverbal", "English", "Other Language"))))+
  theme_classic()+
  labs(x= "Time (s)", y="Scaled ROI Activity", color="vocal type", fill="vocal type")+
  ggtitle("pMTG Right Cluster") + #update labels
  theme(plot.title = element_text(face="bold", size = 18, hjust=0.5), axis.text=element_text(size=15), axis.title=element_text(size=15))
ggsave('pMTGRallvocaltypes.png', plot = last_plot(), scale=1, dpi=350)
```

```{r}
## Plotting timeseries of other-selected vocal trial Stim 11
timeseries_stimothervocal <- subset(timeseries, Stim == 11) # you can pick any stimuli, but I chose 15 here b/c it is other-selected (i.e. everyone heard it) + it has vocals.

onset_value <- 
  timeseries_stimothervocal %>%
  group_by(SUBID) %>%
  subset(seconds==0.475) %>%
  mutate(
    onset_value = pMTGL_univariatecluster #update ROI here
  )
onset_value <- cbind(onset_value[3],onset_value[28])

timeseries_stimothervocal <- merge(timeseries_stimothervocal, onset_value, by.x="SUBID", by.y="SUBID")
timeseries_stimothervocal <- 
  timeseries_stimothervocal %>%
  group_by(SUBID) %>%
  mutate(
    scaled = ((pMTGL_univariatecluster - onset_value)/sd(pMTGL_univariatecluster)) #update ROI here as well
  )

ggplot(timeseries_stimothervocal, aes(x=round(seconds), y=scaled)) + #to change the ROI you're plotting, change this y-value
  geom_smooth() +
  theme_classic() +
  annotate(xmin = 0, xmax = 3, ymin = -Inf, ymax = Inf, geom = 'rect', alpha = 0.2, fill="#56B4E9") +
  annotate(xmin = 4, xmax = 8, ymin = -Inf, ymax = Inf, geom = 'rect', alpha = 0.2, fill="#56B4E9")+
  annotate(xmin = 9, xmax = 13, ymin = -Inf, ymax = Inf, geom = 'rect', alpha = 0.2, fill="#56B4E9")+
  annotate(xmin = 14, xmax = 20, ymin = -Inf, ymax = Inf, geom = 'rect', alpha = 0.2, fill="#56B4E9")+
  #annotate(geom = "text",x = 11, y= 0,label="Vocals \nPresent", fontface="bold",size=6)
  labs(x= "Time (s)", y="Scaled ROI Activity")+
  ggtitle("Stimulus 11: \"Hurt\"") + #update labels
  theme(plot.title = element_text(face="bold", size = 18, hjust=0.5), axis.text=element_text(size=15), axis.title=element_text(size=15))

ggsave('pMTGLStim11.png', plot = last_plot(), scale=1, dpi=350)

```

```{r}
## Plotting timeseries of other-selected vocal trial
timeseries_stimothervocal <- subset(timeseries, Stim == 8) # you can pick any stimuli, but I chose 15 here b/c it is other-selected (i.e. everyone heard it) + it has vocals.

onset_value <- 
  timeseries_stimothervocal %>%
  group_by(SUBID) %>%
  subset(seconds==0.475) %>%
  mutate(
    onset_value = pMTGR_univariatecluster #update ROI here
  )
onset_value <- cbind(onset_value[3],onset_value[28])

timeseries_stimothervocal <- merge(timeseries_stimothervocal, onset_value, by.x="SUBID", by.y="SUBID")
timeseries_stimothervocal <- 
  timeseries_stimothervocal %>%
  group_by(SUBID) %>%
  mutate(
    scaled = ((pMTGR_univariatecluster - onset_value)/sd(pMTGR_univariatecluster)) #update ROI here as well
  )

ggplot(timeseries_stimothervocal, aes(x=round(seconds), y=scaled)) + #to change the ROI you're plotting, change this y-value
  geom_smooth() +
  theme_classic() +
  annotate(xmin = 0, xmax = 15, ymin = -Inf, ymax = Inf, geom = 'rect', alpha = 0.2, fill="#56B4E9") +
  #annotate(geom = "text",x = 11, y= 0,label="Vocals \nPresent", fontface="bold",size=6)
  labs(x= "Time (s)", y="Scaled ROI Activity") +
  ggtitle(expression(bold("Stimulus 8: ") * bolditalic("Symphony No. 2, Finale"))) + #update labels
  theme(plot.title = element_text(face="bold", size = 18, hjust=0.5), axis.text=element_text(size=15), axis.title=element_text(size=15))

ggsave('pMTGRStim8.png', plot = last_plot(), scale=1, dpi=350)

```

```{r}
## Plotting timeseries of other-selected vocal trial
timeseries_stimothervocal <- subset(timeseries, Stim == 10) # you can pick any stimuli, but I chose 15 here b/c it is other-selected (i.e. everyone heard it) + it has vocals.

onset_value <- 
  timeseries_stimothervocal %>%
  group_by(SUBID) %>%
  subset(seconds==0.475) %>%
  mutate(
    onset_value = pMTGR_univariatecluster #update ROI here
  )
onset_value <- cbind(onset_value[3],onset_value[28])

timeseries_stimothervocal <- merge(timeseries_stimothervocal, onset_value, by.x="SUBID", by.y="SUBID")
timeseries_stimothervocal <- 
  timeseries_stimothervocal %>%
  group_by(SUBID) %>%
  mutate(
    scaled = ((pMTGR_univariatecluster - onset_value)/sd(pMTGR_univariatecluster)) #update ROI here as well
  )

ggplot(timeseries_stimothervocal, aes(x=round(seconds), y=scaled)) + #to change the ROI you're plotting, change this y-value
  geom_smooth() +
  theme_classic() +
  annotate(xmin = 0, xmax = 17, ymin = -Inf, ymax = Inf, geom = 'rect', alpha = 0.2, fill="#56B4E9") +
  #annotate(geom = "text",x = 11, y= 0,label="Vocals \nPresent", fontface="bold",size=6)
  labs(x= "Time (s)", y="Scaled ROI Activity")+
  ggtitle("Stimulus 10: \"John Wayne Gacy, Jr.\"") + #update labels
  theme(plot.title = element_text(face="bold", size = 18, hjust=0.5), axis.text=element_text(size=15), axis.title=element_text(size=15))

ggsave('pMTGRStim10.png', plot = last_plot(), scale=1, dpi=350)

```

```{r}
## Plotting timeseries of other-selected vocal trial Stim 12,13,15
timeseries_stimothervocal <- subset(timeseries, Stim == 15) # you can pick any stimuli, but I chose 15 here b/c it is other-selected (i.e. everyone heard it) + it has vocals.

onset_value <- 
  timeseries_stimothervocal %>%
  group_by(SUBID) %>%
  subset(seconds==0.475) %>%
  mutate(
    onset_value = pMTGR_univariatecluster #update ROI here
  )
onset_value <- cbind(onset_value[3],onset_value[28])

timeseries_stimothervocal <- merge(timeseries_stimothervocal, onset_value, by.x="SUBID", by.y="SUBID")
timeseries_stimothervocal <- 
  timeseries_stimothervocal %>%
  group_by(SUBID) %>%
  mutate(
    scaled = ((pMTGR_univariatecluster - onset_value)/sd(pMTGR_univariatecluster)) #update ROI here as well
  )

ggplot(timeseries_stimothervocal, aes(x=round(seconds), y=scaled)) + #to change the ROI you're plotting, change this y-value
  geom_smooth() +
  theme_classic() +
  annotate(xmin = 0, xmax = 20, ymin = -Inf, ymax = Inf, geom = 'rect', alpha = 0.2, fill="#56B4E9") +
  #annotate(geom = "text",x = 11, y= 0,label="Vocals \nPresent", fontface="bold",size=6)
  labs(x= "Time (s)", y="Scaled ROI Activity")+
  ggtitle(expression(bold("Stimulus 15: ") * bolditalic("Nessun Dorma"))) + #update labels
  theme(plot.title = element_text(face="bold", size = 18, hjust=0.5), axis.text=element_text(size=15), axis.title=element_text(size=15))

ggsave('pMTGRStim15.png', plot = last_plot(), scale=1, dpi=350)

```

#investigating differences in liking + familiarity
```{r}
vocal_nonvocal_other <- 
  vocal_nonvocal %>%
  subset(self_other=="other") %>%
  subset(MCI!="Y")

m1 <- lmer(liking ~ vocal + older_younger + (1|participant_ID), data=vocal_nonvocal_other)
summary(m1)

m1 <- lmer(familiarity ~ vocal + older_younger + (1|participant_ID), data=vocal_nonvocal_other)
summary(m1)
```