---
title: "data-cleaning"
author: "Nick Kathios"
date: '2022-12-01'
output: html_document
---
#load packages 
```{r}
library(tidyverse)
```
#read in data
```{r}
vocal_nonvocal<- read.csv('../nickkathios/Downloads/vocal_nonvocal.csv')
roidata <- read.csv('../nickkathios/Downloads/roidata.csv')
roistim_order <- read.csv('../nickkathios/Downloads/roi_participantorder.csv')
```

#get TRs w/ coded data
```{r}
ID = Sys.glob('/Users/nickkathios/Downloads/MRI_mus-bid_task/**********1_mus-bid-biddata.txt')
post_df = ID %>% 
  map_dfr(read_table, .id = "source")


post_df$source <- as.integer(post_df$source)
source <- seq(1,71,by=1)
ID <- cbind(source,ID)

post_df <- merge(post_df, ID, by.y ="source", by.x="source") 

post_df$ID <-  gsub("1_mus-bid-biddata.txt", "", post_df$ID)
post_df$ID <-  gsub("/Users/nickkathios/Downloads/MRI_mus-bid_task/", "", post_df$ID)

names(post_df)<- c("Source", "Stim", "Liking", "Familiarity", "SUBID")

post_df<- subset(post_df, select=c("Stim", "SUBID"))
#to do: merge w/ vocal-nonvocal & expand df to have all TRs
post_df$SUBID<-gsub('[[:digit:]]+', '',post_df$SUBID)
onsets_stim <- merge(post_df, vocal_nonvocal, by.x=c("SUBID", "Stim"), by.y=c("participant_ID", "stim_ID"))


stim_order <- seq(1,24,1)
stim_order <- as.data.frame(rep(stim_order, 60))
TRs<- as.data.frame(seq(1,1440,1))
names(stim_order) <- "order"
names(TRs) <- "TR"

stim_order$order <- arrange(stim_order, order)
TRs <- cbind(stim_order$order, TRs)

TRs_vocalnonvocal<-merge(TRs, onsets_stim, by.x="order",by.y="stim_order")
```

#cleaning ROI-stim orde
```{r}
roi_ID <- seq(1,71,1)
roi_ID <- as.data.frame(rep(roi_ID, 1440))
names(roi_ID) <- "ID"
roi_ID <- arrange(roi_ID, ID)

roi_data<-cbind(roi_ID, roidata)
TRs<- (seq(1,1440,1))
TRs_roi<- as.data.frame(rep(TRs, 71))
names(TRs_roi) <- "TR"
roi_data<-cbind(TRs_roi, roi_data)
```

#merge coded data w/ TRs
```{r}
#merge
roistim_order <- subset(roistim_order, roi_order <= 18 | roi_order >= 36)

roi_dataID<- merge(roi_data, roistim_order, by.x = "ID", by.y="roi_order")

attempt <- merge(TRs_vocalnonvocal, roi_dataID, by.x=c("TR", "SUBID"), by.y=c("TR","SUBID"))

#isolate just music-listening TR
x=1:77760
for (i in x){
  if (attempt$TR[i] >= (60*(attempt$order[i]-1)+43) & attempt$TR[i] <= (60*(attempt$order[i]-1)+60)){
    attempt$TR[i] = NA
  }
}

attempt<-attempt[!is.na(attempt$TR),]
attempt<-subset(attempt, Stim < 17)

roi_timeseries <- write.csv(attempt, file="roitimeseries.csv")
```

